### ISSUE TITLE
Fix testDatetimeISO test in Dates2Test

### ISSUE THREAD

**Issue by fabianerik** [BME-MIT-IET/TBD-iet-2019#18]
Test failing on Travis due to wrong timezone

**Comment by marcellpaluska** [comment]
Before:
<img width="825" alt="Képernyőfotó 2019-05-20 - 20 40 19" src="https://user-images.githubusercontent.com/31635318/58044213-8372b680-7b3f-11e9-8c52-a8129819d604.png">

**Comment by marcellpaluska** [comment]
Now:
<img width="1081" alt="Képernyőfotó 2019-05-20 - 20 58 48" src="https://user-images.githubusercontent.com/31635318/58045387-9e92f580-7b42-11e9-87a3-3f6fe2357cb8.png">
